name: Build and Deploy
on: 
  workflow_dispatch: 
permissions:
  contents: read
  security-events: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v4
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build -t myapp:latest .
      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Push to ACR
        run: |
          az acr login -n labdeploy-webapp-bram
          docker tag myapp:latest labdeployacrbram.azurecr.io/myapp:latest
          docker push labdeployacrbram.azurecr.io/myapp:latest
      - name: Deploy to WebApp
        run: |
          az webapp config container set \
          -g RGLabDeploy-bram \
          -n labdeploy-webapp-bram \
          --container-image-name labdeployacrbram.azurecr.io/myapp:latest \
          --container-registry-url https://labdeployacrbram.azurecr.io \
          --container-registry-user ${{secrets.ACR_USER}} \
          --container-registry-password ${{secrets.ACR_PWD}}
